/**
 * ExportReportModal.jsx
 * Optimization Report Preview modal.
 * Renders conditionally based on isExportModalOpen from Zustand store.
 * Dark/light mode dual classes throughout.
 */

import { useState } from "react";
import { X, Download, Database, Zap } from "./Icons.jsx";
import { useOptimizationStore } from "../store/useOptimizationStore";
import { SqlCodeBlock } from "./SqlCodeBlock.jsx";

const RULE_DISPLAY_NAMES = {
  predicate_pushdown: "Predicate Pushdown",
  projection_pruning: "Projection Pruning",
  join_reordering: "Join Reordering",
  subquery_unnesting: "Subquery Unnesting",
  aggregation_pushdown: "Aggregation Pushdown",
  redundant_join_elimination: "Redundant Join Elimination",
};

function SummaryCard({ label, value, unit = "", highlight = false }) {
  return (
    <div className={`
      rounded-xl p-4 text-center
      ${highlight
        ? "bg-green-500/5 border border-green-500/15"
        : "bg-[#111827] border border-white/5"
      }
    `}>
      <div className="text-[10px] font-semibold text-gray-500 uppercase tracking-widest mb-1.5">
        {label}
      </div>
      <div className={`text-[22px] font-bold font-mono leading-none
        ${highlight ? "text-green-400" : "text-gray-100"}
      `}>
        {value}
        {unit && <span className="text-[13px] font-normal text-gray-500 ml-0.5">{unit}</span>}
      </div>
    </div>
  );
}

export function ExportReportModal({ data }) {
  const { isExportModalOpen, closeExportModal } = useOptimizationStore();
  const [format, setFormat] = useState("pdf");

  if (!isExportModalOpen) return null;

  const best = data?.candidates?.find(
    (c) => c.id === data?.recommendation?.best_candidate_id
  );
  const allRules = [
    ...new Set(
      (data?.candidates || [])
        .filter((c) => !c.is_original)
        .flatMap((c) => c.rules_applied || [])
    ),
  ];

  const origMetrics = best?.plan_comparison?.original?.metrics;
  const rewMetrics = best?.plan_comparison?.rewritten?.metrics;

  const costReductionPct =
    origMetrics && rewMetrics && origMetrics.total_cost > 0
      ? ((origMetrics.total_cost - rewMetrics.total_cost) / origMetrics.total_cost) * 100
      : 0;
  const timeSavedMs =
    origMetrics && rewMetrics
      ? Math.max(0, origMetrics.estimated_time_ms - rewMetrics.estimated_time_ms)
      : 0;

  const queryId = data?.query_id || "—";
  const date = data?.timestamp
    ? new Date(data.timestamp).toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      })
    : new Date().toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      });

  const handleDownload = () => {
    const sql = best?.sql || data?.recommendation?.best_sql || "";

    if (format === "json") {
      const payload = JSON.stringify(data, null, 2);
      const blob = new Blob([payload], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `optimization-report-${queryId}.json`;
      a.click();
      URL.revokeObjectURL(url);
      return;
    }

    // Markdown (default)
    const md = `# Optimization Report

**Query ID:** ${queryId}
**Date:** ${date}
**Database:** PostgreSQL (tpch)

---

## Summary

| Metric | Value |
|--------|-------|
| Total Rules Applied | ${allRules.length} |
| Cost Reduction | ${costReductionPct.toFixed(1)}% |
| Time Saved | ${timeSavedMs} ms |

---

## Applied Rules

${allRules
  .map((r, i) => `${i + 1}. **${RULE_DISPLAY_NAMES[r] || r}**`)
  .join("\n")}

---

## Final Optimized SQL

\`\`\`sql
${sql}
\`\`\`

*Generated by LLM-R2 Enhanced*
`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `optimization-report-${queryId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ backgroundColor: "rgba(0,0,0,0.72)", backdropFilter: "blur(4px)" }}
    >
      {/* Modal container */}
      <div className="
        relative w-full max-w-4xl max-h-[90vh] rounded-2xl
        flex flex-col
        bg-[#0B0F19] border border-white/10
        shadow-2xl shadow-black/60
        overflow-hidden
      ">
        {/* Header */}
        <div className="
          flex items-center justify-between px-6 py-4
          border-b border-white/5 shrink-0
        ">
          <div className="flex items-center gap-3">
            <div className="
              w-8 h-8 rounded-lg flex items-center justify-center shrink-0
              bg-purple-500/10 border border-purple-500/20
            ">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
                className="text-purple-400">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="16" y1="13" x2="8" y2="13"/>
                <line x1="16" y1="17" x2="8" y2="17"/>
                <polyline points="10 9 9 9 8 9"/>
              </svg>
            </div>
            <div>
              <h2 className="text-[14px] font-semibold text-gray-100">
                Optimization Report
              </h2>
              <p className="text-[11px] text-gray-500">
                Review before downloading
              </p>
            </div>
          </div>
          <button
            onClick={closeExportModal}
            className="
              w-8 h-8 rounded-lg flex items-center justify-center
              text-gray-500 hover:text-gray-200 hover:bg-white/5
              transition-colors
            "
          >
            <X size={16} />
          </button>
        </div>

        {/* Document body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 custom-scrollbar">

          {/* Meta info */}
          <div className="
            grid grid-cols-3 gap-3 mb-5
            px-4 py-3 rounded-xl
            bg-[#111827] border border-white/5
          ">
            <div>
              <div className="text-[9px] font-semibold text-gray-500 uppercase tracking-widest mb-0.5">
                Query ID
              </div>
              <div className="text-[11px] font-mono text-gray-300">{queryId}</div>
            </div>
            <div>
              <div className="text-[9px] font-semibold text-gray-500 uppercase tracking-widest mb-0.5">
                Date
              </div>
              <div className="text-[11px] text-gray-300">{date}</div>
            </div>
            <div>
              <div className="text-[9px] font-semibold text-gray-500 uppercase tracking-widest mb-0.5">
                Database
              </div>
              <div className="text-[11px] text-gray-300">tpch · PostgreSQL</div>
            </div>
          </div>

          {/* Summary grid */}
          <div className="mb-5">
            <div className="flex items-center gap-2 mb-3">
              <Zap size={13} className="text-purple-400" />
              <h3 className="text-[11px] font-semibold text-gray-400 uppercase tracking-widest">
                Analysis Summary
              </h3>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <SummaryCard label="Total Rules Applied" value={allRules.length} />
              <SummaryCard
                label="Cost Reduced"
                value={costReductionPct.toFixed(1)}
                unit="%"
                highlight={costReductionPct > 0}
              />
              <SummaryCard
                label="Time Saved"
                value={timeSavedMs}
                unit="ms"
                highlight={timeSavedMs > 0}
              />
            </div>
          </div>

          {/* Rule Execution Trace */}
          <div className="mb-5">
            <div className="flex items-center gap-2 mb-3">
              <Database size={13} className="text-purple-400" />
              <h3 className="text-[11px] font-semibold text-gray-400 uppercase tracking-widest">
                Rule Execution Trace
              </h3>
            </div>
            <div className="space-y-2">
              {allRules.length > 0 ? (
                allRules.map((rule, i) => {
                  const rec = data?.rule_recommendations?.recommendations?.find(
                    (r) => r.rule === rule
                  );
                  return (
                    <div key={rule} className="flex gap-3">
                      {/* Step number */}
                      <div className="
                        shrink-0 w-6 h-6 rounded-full mt-0.5
                        flex items-center justify-center
                        bg-purple-500/10 border border-purple-500/20 text-purple-400
                        text-[10px] font-bold
                      ">
                        {i + 1}
                      </div>
                      {/* Content */}
                      <div className="
                        flex-1 rounded-xl p-3
                        bg-[#111827] border border-white/5
                      ">
                        <div className="text-[11px] font-semibold text-purple-300 mb-1">
                          {RULE_DISPLAY_NAMES[rule] || rule.replace(/_/g, " ")}
                        </div>
                        <div className="text-[11px] text-gray-400 leading-relaxed">
                          {rec?.reason || "Rule applied successfully."}
                        </div>
                        {rec?.reason && (
                          <div className="mt-1.5 text-[10px] text-green-400/70 flex items-center gap-1.5">
                            <span className="w-1.5 h-1.5 rounded-full bg-green-400 shrink-0" />
                            {rec.reason}
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })
              ) : (
                <p className="text-[12px] text-gray-600 italic py-3">
                  No rules applied.
                </p>
              )}
            </div>
          </div>

          {/* Final SQL */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <svg width="13" height="13" viewBox="0 0 16 16" fill="none"
                stroke="#60a5fa" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <rect x="3" y="7.5" width="10" height="7" rx="1.5" />
                <path d="M5.5 7.5 V5 a2.5 2.5 0 0 1 5 0 V7.5" />
              </svg>
              <h3 className="text-[11px] font-semibold text-gray-400 uppercase tracking-widest">
                Final Optimized SQL
              </h3>
            </div>
            <div className="rounded-xl overflow-hidden border border-white/5">
              <div className="px-4 py-2 bg-[#0D1117] border-b border-white/5">
                <span className="text-[10px] font-mono text-gray-600">optimized.sql</span>
              </div>
              <SqlCodeBlock
                code={best?.sql || data?.recommendation?.best_sql || ""}
              />
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="
          flex items-center justify-end gap-3 px-6 py-4
          border-t border-white/5 shrink-0 bg-[#0B0F19]
        ">
          <span className="text-[11px] text-gray-500">Format:</span>
          <select
            value={format}
            onChange={(e) => setFormat(e.target.value)}
            className="
              px-3 py-1.5 rounded-lg text-[12px]
              bg-[#111827] border border-white/10
              text-gray-300 focus:outline-none focus:border-purple-500/30
              cursor-pointer
            "
          >
            <option value="json">JSON</option>
            <option value="markdown">Markdown</option>
          </select>
          <button
            onClick={handleDownload}
            className="
              flex items-center gap-2 px-5 py-2 rounded-xl
              text-[12px] font-semibold text-white
              bg-green-500 hover:bg-green-400
              transition-all shadow-lg shadow-green-500/20
            "
          >
            <Download size={14} />
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
}

export default ExportReportModal;
